build:
  maxIssues: 0

complexity:
  LongParameterList:
    functionThreshold: 10
    ignoreDefaultParameters: true
  ComplexCondition:
    threshold: 5

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'

style:
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
